name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Delete Docker Image and Containers
        run: sudo docker rm -f uutrue

      - name: Pull Docker Image from Docker hub
        run: sudo docker pull uutrue512/songdo:latest

      - name: Execute Docker Container
        run: sudo docker run -d -p 80:3000 --name uutrue uutrue512/songdo:latest

